export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const SIGNUP_EMAIL_CHANGED = 'SIGNUP_EMAIL_CHANGED';
export const SIGNUP_PASSWORD_CHANGED = 'SIGNUP_PASSWORD_CHANGED';
export const LOGIN_PRESS = 'LOGIN_PRESS';
export const SIGNUP_PRESS = 'SIGNUP_PRESS';
export const LOGOUT_USER = 'LOGOUT_USER';
